import { NavBar } from '../../components/organisms/Navbar.tsx/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='bg-blue-100'>{children}</body>
    </html>
  );
}
